import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";
import { Header } from "~/components/Header";
import { Bookings } from "~/components/Bookings";
import { BeatLoader } from "react-spinners";
import Image from "next/image";

const Home: NextPage = () => {
  const { isInitialLoading: isInitialLoadingBookings, data: bookings } =
    api.booking.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Beach bookings</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="dark:bg-black">
        <div className="min-w-sm flex min-w-fit flex-col bg-gradient-to-b from-[#2e026d] to-[#15162c]">
          <Bookings />
        </div>
      </main>
    </>
  );
};

export default Home;
